// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: offlineDownloadTest

#include <stdio.h>
#include "ui.h"
#include "ui_helpers.h"
//#include "src/lv_100ask_file_explorer/lv_100ask_file_explorer.h"
#include "FreeRTOS.h"
#include "cmsis_os.h"
#include "lv_lib_100ask.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
lv_obj_t * ui_Label1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES


// SCREEN: ui_OfflineDownload
void ui_OfflineDownload_screen_init(void);
void ui_event_OfflineDownload(lv_event_t * e);
lv_obj_t * ui_OfflineDownload;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label3;
void ui_event_TypeSelectBtn(lv_event_t * e);
lv_obj_t * ui_TypeSelectBtn;
lv_obj_t * ui_Label4;
void ui_event_BinSelectBtn(lv_event_t * e);
lv_obj_t * ui_BinSelectBtn;
lv_obj_t * ui_Label5;
void ui_event_StartBtn(lv_event_t * e);
lv_obj_t * ui_StartBtn;
lv_obj_t * ui_Label6;
lv_obj_t * ui_panel3;
lv_obj_t * ui_SelectChipType;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_SelectBin;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_SuccessCount;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_uiOfflineDownloadProcessBar;
lv_obj_t * ui_uiOfflineDownloadProcessNum;
// CUSTOM VARIABLES


// SCREEN: ui_FileExplorer
void ui_FileExplorer_screen_init(void);
lv_obj_t * ui_FileExplorer;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

//代表当前选择的文件路径是返回到哪里，0表示未初始化，1表示返回到芯片型号选择，2表示返回到选择固件。
uint8_t current_path_return = 0;
extern char choose_device_path[LV_100ASK_FILE_EXPLORER_PATH_MAX_LEN];
extern char choose_firmware_bin_path[LV_100ASK_FILE_EXPLORER_PATH_MAX_LEN];

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OfflineDownload, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_OfflineDownload_screen_init);
    }
}

void ui_event_OfflineDownload(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_TypeSelectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        current_path_return = 1;//返回到芯片型号选择
        _ui_screen_change(&ui_FileExplorer, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FileExplorer_screen_init);
    }
}

void ui_event_BinSelectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        current_path_return = 2;//返回到选择固件
        _ui_screen_change(&ui_FileExplorer, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FileExplorer_screen_init);
    }
}

extern QueueHandle_t offline_download_sem;//离线下载二值信号量句柄
void ui_event_StartBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        xSemaphoreGive(offline_download_sem);//释放二值信号量开始下载
        LV_LOG_USER("Start download");
    }
}

//文件管理器事件处理
char current_path[LV_100ASK_FILE_EXPLORER_PATH_MAX_LEN] = {0};
void file_explorer_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);

    if(code == LV_EVENT_VALUE_CHANGED) {
        char * cur_path =  lv_100ask_file_explorer_get_cur_path(obj);
        char * sel_fn = lv_100ask_file_explorer_get_sel_fn(obj);
        _ui_screen_change(&ui_OfflineDownload,LV_SCR_LOAD_ANIM_FADE_ON,500,0,&ui_OfflineDownload_screen_init);
        LV_LOG_USER("%s,%s", cur_path, sel_fn);
        if(current_path_return == 1)//返回到芯片型号选择
        {
            current_path_return = 0;
            strtok(cur_path, "/");//0:/
            snprintf(current_path, sizeof(current_path), "%s/%s", cur_path,sel_fn);//0:/xxx
            strncpy(choose_device_path, current_path,
                       sizeof(current_path));
            LV_LOG_USER("choose_device_path:%s", choose_device_path);
            lv_label_set_text(ui_SelectChipType, choose_device_path);
        }
        else if(current_path_return == 2)//返回到固件选择
        {
           current_path_return = 0;
            strtok(cur_path, "/");
            snprintf(current_path, sizeof(current_path), "%s/%s", cur_path,sel_fn);
            strncpy(choose_firmware_bin_path, current_path,
                       sizeof(current_path));
            lv_label_set_text(ui_SelectBin, choose_firmware_bin_path);
        }
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_OfflineDownload_screen_init();
    ui_FileExplorer_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
