// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#ifndef _HONESTLINK_UI_H
#define _HONESTLINK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "pageManager.h"

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
void ui_HomeScreen_screen_deinit(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_Container1;
void ui_event_PinMapPanel(lv_event_t * e);
extern lv_obj_t * ui_PinMapPanel;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label1;
void ui_event_AboutPanel3(lv_event_t * e);
extern lv_obj_t * ui_AboutPanel3;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Image9;
void ui_event_PWMPanel(lv_event_t * e);
extern lv_obj_t * ui_PWMPanel;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label3;
void ui_event_ElectricPanel(lv_event_t * e);
extern lv_obj_t * ui_ElectricPanel;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
void ui_event_ServoisPanel(lv_event_t * e);
extern lv_obj_t * ui_ServoisPanel;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
void ui_event_LogicPanel(lv_event_t * e);
extern lv_obj_t * ui_LogicPanel;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label6;
void ui_event_DACPanel(lv_event_t * e);
extern lv_obj_t * ui_DACPanel;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_OfflineScreen
void ui_OfflineScreen_screen_init(void);
void ui_OfflineScreen_screen_deinit(void);
void ui_event_OfflineScreen(lv_event_t * e);
void ui_event_OfflineChipSelect(lv_event_t *e);
void ui_event_OfflineFirmSelect(lv_event_t *e);
void ui_event_OfflineFirmDownload(lv_event_t * e);
extern lv_obj_t * ui_OfflineScreen;
extern lv_obj_t * ui_SelectChip;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_SelectFirm;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_FirmDown;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_ChipLabel;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_FirmWareLabel;
extern lv_obj_t * ui_DownBar;
extern lv_obj_t * ui_DownProgress;
extern lv_obj_t * ui_DownInfo;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Label47;
// CUSTOM VARIABLES

// SCREEN: ui_PinMapScreen
void ui_PinMapScreen_screen_init(void);
void ui_PinMapScreen_screen_deinit(void);
void ui_event_PinMapScreen(lv_event_t * e);
extern lv_obj_t * ui_PinMapScreen;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_PWMScreen
void ui_PWMScreen_screen_init(void);
void ui_PWMScreen_screen_deinit(void);
void ui_event_PWMScreen(lv_event_t * e);
extern lv_obj_t * ui_PWMScreen;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * keyboard;
void ui_event_PWMPeriod(lv_event_t * e);
extern lv_obj_t * ui_PWMPeriod;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label33;
void ui_event_PWMPulse(lv_event_t * e);
void ui_event_KeyBoard(lv_event_t *e);
extern lv_obj_t * ui_PWMPulse;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_PWMFreqLabel;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_PWMDutyLabel;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Label51;
// CUSTOM VARIABLES

// SCREEN: ui_ElectricScreen
void ui_ElectricScreen_screen_init(void);
void ui_ElectricScreen_screen_deinit(void);
void ui_event_ElectricScreen(lv_event_t * e);
extern lv_obj_t * ui_ElectricScreen;
extern lv_obj_t * ui_VoltageChart;
extern lv_obj_t * ui_CurrentChart;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_VoltageLabel;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_CurrentLabel;
// CUSTOM VARIABLES

// SCREEN: ui_ServosScreen
void ui_ServosScreen_screen_init(void);
void ui_ServosScreen_screen_deinit(void);
void ui_event_ServosScreen(lv_event_t * e);
extern lv_obj_t * ui_ServosScreen;
extern lv_obj_t * ui_ServoArc;
extern lv_obj_t * ui_ServoLabel;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Label64;
// CUSTOM VARIABLES

// SCREEN: ui_LogicScreen
void ui_LogicScreen_screen_init(void);
void ui_LogicScreen_screen_deinit(void);
void ui_event_LogicScreen(lv_event_t * e);
extern lv_obj_t * ui_LogicScreen;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Panel38;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Panel39;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_Panel40;
extern lv_obj_t * ui_Label70;
extern lv_obj_t * ui_Panel41;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Panel42;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Panel43;
extern lv_obj_t * ui_Label73;
extern lv_obj_t * ui_Panel44;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_Panel45;
extern lv_obj_t * ui_Label75;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label76;
// CUSTOM VARIABLES

// SCREEN: ui_DACScreen
void ui_DACScreen_screen_init(void);
void ui_DACScreen_screen_deinit(void);
void ui_event_DACScreen(lv_event_t * e);
extern lv_obj_t * ui_DACScreen;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Label77;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Panel46;
extern lv_obj_t * ui_Label78;
extern lv_obj_t * ui_DACFreq;
// CUSTOM VARIABLES

// SCREEN: ui_FileExplorerScreen
void ui_FileExplorerScreen_screen_init(void);
void ui_FileExplorerScreen_screen_deinit(void);
extern lv_obj_t * ui_FileExplorerScreen;
void file_explorer_event_handler(lv_event_t *e);
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pinmap_png);    // assets/PinMap.png
LV_IMG_DECLARE(ui_img_offline_png);    // assets/Offline.png
LV_IMG_DECLARE(ui_img_pwm_png);    // assets/PWM.png
LV_IMG_DECLARE(ui_img_electric_png);    // assets/Electric.png
LV_IMG_DECLARE(ui_img_servos_png);    // assets/Servos.png
LV_IMG_DECLARE(ui_img_logic_png);    // assets/Logic.png
LV_IMG_DECLARE(ui_img_waveform_png);    // assets/waveform.png
LV_IMG_DECLARE(ui_img_voltage_png);    // assets/Voltage.png
LV_IMG_DECLARE(ui_img_current_png);    // assets/current.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
