// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: offlineDownloadTest

#ifndef _OFFLINEDOWNLOADTEST_UI_H
#define _OFFLINEDOWNLOADTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Label1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_OfflineDownload
void ui_OfflineDownload_screen_init(void);
void ui_event_OfflineDownload(lv_event_t * e);
extern lv_obj_t * ui_OfflineDownload;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
void ui_event_TypeSelectBtn(lv_event_t * e);
extern lv_obj_t * ui_TypeSelectBtn;
extern lv_obj_t * ui_Label4;
void ui_event_BinSelectBtn(lv_event_t * e);
extern lv_obj_t * ui_BinSelectBtn;
extern lv_obj_t * ui_Label5;
void ui_event_StartBtn(lv_event_t * e);
extern lv_obj_t * ui_StartBtn;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_panel3;
extern lv_obj_t * ui_SelectChipType;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_SelectBin;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_SuccessCount;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_uiOfflineDownloadProcessBar;
extern lv_obj_t * ui_uiOfflineDownloadProcessNum;
// CUSTOM VARIABLES

// SCREEN: ui_FileExplorer
void ui_FileExplorer_screen_init(void);
void file_explorer_event_handler(lv_event_t * e);
extern lv_obj_t * ui_FileExplorer;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
