// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#include "../ui.h"

void ui_DACScreen_screen_init(void)
{
    ui_DACScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DACScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel37 = lv_obj_create(ui_DACScreen);
    lv_obj_set_width(ui_Panel37, 177);
    lv_obj_set_height(ui_Panel37, 39);
    lv_obj_set_x(ui_Panel37, -1);
    lv_obj_set_y(ui_Panel37, -82);
    lv_obj_set_align(ui_Panel37, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel37, lv_color_hex(0x52E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label77 = lv_label_create(ui_Panel37);
    lv_obj_set_width(ui_Label77, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label77, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label77, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label77, "Output Waveform");

    ui_Dropdown1 = lv_dropdown_create(ui_DACScreen);
    lv_dropdown_set_options(ui_Dropdown1,
                            "Sine wave\nSquare wave\nTriangle wave\nTrapezoid wave\nRising Sawtooth wave\nFalling Sawtooth wave\n");
    lv_obj_set_width(ui_Dropdown1, 177);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, -37);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Panel46 = lv_obj_create(ui_DACScreen);
    lv_obj_set_width(ui_Panel46, 177);
    lv_obj_set_height(ui_Panel46, 39);
    lv_obj_set_x(ui_Panel46, 1);
    lv_obj_set_y(ui_Panel46, 9);
    lv_obj_set_align(ui_Panel46, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel46, lv_color_hex(0x52E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label78 = lv_label_create(ui_Panel46);
    lv_obj_set_width(ui_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label78, "Output Frequency");

    ui_DACFreq = lv_textarea_create(ui_DACScreen);
    lv_obj_set_width(ui_DACFreq, 175);
    lv_obj_set_height(ui_DACFreq, 44);
    lv_obj_set_x(ui_DACFreq, 3);
    lv_obj_set_y(ui_DACFreq, 62);
    lv_obj_set_align(ui_DACFreq, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_DACFreq, "Frequency...");



    lv_obj_add_event_cb(ui_DACScreen, ui_event_DACScreen, LV_EVENT_ALL, NULL);

}
