// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#include "../ui.h"

Page_t Page_Electric = {
        .id = ElectricPage,
        .init = ui_ElectricScreen_screen_init,
        .deinit = ui_ElectricScreen_screen_deinit,
        .page_obj = &ui_ElectricScreen,
};

void ui_ElectricScreen_screen_init(void) {
    ui_ElectricScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ElectricScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VoltageChart = lv_chart_create(ui_ElectricScreen);
    lv_obj_set_width(ui_VoltageChart, 229);
    lv_obj_set_height(ui_VoltageChart, 53);
    lv_obj_set_x(ui_VoltageChart, 1);
    lv_obj_set_y(ui_VoltageChart, 2);
    lv_obj_set_align(ui_VoltageChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_VoltageChart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_VoltageChart, LV_CHART_AXIS_PRIMARY_Y, 0, 30);
    lv_chart_set_axis_tick(ui_VoltageChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_VoltageChart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 0, 2, true, 50);
    lv_chart_set_axis_tick(ui_VoltageChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 2, false, 25);
    lv_chart_series_t *ui_VoltageChart_series_1 = lv_chart_add_series(ui_VoltageChart, lv_color_hex(0x808080),
                                                                      LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_VoltageChart_series_1_array[] = {0, 10, 20, 30, 25, 27, 10, 20, 10, 0, 3, 0};
    lv_chart_set_ext_y_array(ui_VoltageChart, ui_VoltageChart_series_1, ui_VoltageChart_series_1_array);


    ui_CurrentChart = lv_chart_create(ui_ElectricScreen);
    lv_obj_set_width(ui_CurrentChart, 228);
    lv_obj_set_height(ui_CurrentChart, 53);
    lv_obj_set_x(ui_CurrentChart, 0);
    lv_obj_set_y(ui_CurrentChart, 68);
    lv_obj_set_align(ui_CurrentChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_CurrentChart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_CurrentChart, LV_CHART_AXIS_PRIMARY_Y, 0, 30);
    lv_chart_set_axis_tick(ui_CurrentChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_CurrentChart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 0, 2, true, 50);
    lv_chart_set_axis_tick(ui_CurrentChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 2, false, 25);
    lv_chart_series_t *ui_CurrentChart_series_1 = lv_chart_add_series(ui_CurrentChart, lv_color_hex(0x808080),
                                                                      LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_CurrentChart_series_1_array[] = {0, 10, 20, 30, 25, 27, 10, 20, 10, 0, 3, 0};
    lv_chart_set_ext_y_array(ui_CurrentChart, ui_CurrentChart_series_1, ui_CurrentChart_series_1_array);


    ui_Panel31 = lv_obj_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Panel31, 37);
    lv_obj_set_height(ui_Panel31, 28);
    lv_obj_set_x(ui_Panel31, 5);
    lv_obj_set_y(ui_Panel31, 121);
    lv_obj_set_align(ui_Panel31, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel31, lv_color_hex(0xF80F1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Panel31);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, 0);
    lv_obj_set_y(ui_Label52, 1);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "C-:3");

    ui_Panel28 = lv_obj_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Panel28, 37);
    lv_obj_set_height(ui_Panel28, 28);
    lv_obj_set_x(ui_Panel28, 46);
    lv_obj_set_y(ui_Panel28, 122);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0x080601), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Panel28);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -1);
    lv_obj_set_y(ui_Label49, 0);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "C+:4");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel32 = lv_obj_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Panel32, 37);
    lv_obj_set_height(ui_Panel32, 28);
    lv_obj_set_x(ui_Panel32, 89);
    lv_obj_set_y(ui_Panel32, 123);
    lv_obj_set_align(ui_Panel32, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel32, lv_color_hex(0xFC1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -2);
    lv_obj_set_y(ui_Label53, 0);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "V: 5");

    ui_Label54 = lv_label_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -85);
    lv_obj_set_y(ui_Label54, 121);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "ROM1");

    ui_Image10 = lv_img_create(ui_ElectricScreen);
    lv_img_set_src(ui_Image10, &ui_img_voltage_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -86);
    lv_obj_set_y(ui_Image10, -107);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 130);

    ui_Image1 = lv_img_create(ui_ElectricScreen);
    lv_img_set_src(ui_Image1, &ui_img_current_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -86);
    lv_obj_set_y(ui_Image1, -56);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 130);

    ui_Label56 = lv_label_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 84);
    lv_obj_set_y(ui_Label56, -105);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "V");
    lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, 84);
    lv_obj_set_y(ui_Label58, -56);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "A");
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel33 = lv_obj_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Panel33, 127);
    lv_obj_set_height(ui_Panel33, 41);
    lv_obj_set_x(ui_Panel33, 4);
    lv_obj_set_y(ui_Panel33, -104);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VoltageLabel = lv_label_create(ui_Panel33);
    lv_obj_set_width(ui_VoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltageLabel, 2);
    lv_obj_set_y(ui_VoltageLabel, 1);
    lv_obj_set_align(ui_VoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageLabel, "3");
    lv_obj_set_style_text_font(ui_VoltageLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel34 = lv_obj_create(ui_ElectricScreen);
    lv_obj_set_width(ui_Panel34, 127);
    lv_obj_set_height(ui_Panel34, 41);
    lv_obj_set_x(ui_Panel34, 5);
    lv_obj_set_y(ui_Panel34, -57);
    lv_obj_set_align(ui_Panel34, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentLabel = lv_label_create(ui_Panel34);
    lv_obj_set_width(ui_CurrentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentLabel, 2);
    lv_obj_set_y(ui_CurrentLabel, 1);
    lv_obj_set_align(ui_CurrentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentLabel, "1");
    lv_obj_set_style_text_font(ui_CurrentLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ElectricScreen, ui_event_ElectricScreen, LV_EVENT_ALL, NULL);

}

void ui_ElectricScreen_screen_deinit(void) {

}