// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: offlineDownloadTest

#include "../ui.h"
#include "lv_lib_100ask.h"

void ui_FileExplorer_screen_init(void)
{
    ui_FileExplorer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FileExplorer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t *file_explorer = lv_100ask_file_explorer_create(ui_FileExplorer);//创建文件管理器
    lv_100ask_file_explorer_open_dir(file_explorer, "0:/");//输入要挂载的目录
    lv_obj_add_event_cb(file_explorer, file_explorer_event_handler, LV_EVENT_VALUE_CHANGED, NULL);//添加事件回调
}
