// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#include "../ui.h"
#include "pageManager.h"

Page_t page_Home = {.init = ui_HomeScreen_screen_init,.deinit = ui_HomeScreen_screen_deinit,.page_obj = &ui_HomeScreen};


void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_PinMapPanel = lv_obj_create(ui_Container1);
    lv_obj_set_height(ui_PinMapPanel, 100);
    lv_obj_set_width(ui_PinMapPanel, lv_pct(100));
    lv_obj_set_x(ui_PinMapPanel, 8);
    lv_obj_set_y(ui_PinMapPanel, -1);
    lv_obj_set_align(ui_PinMapPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PinMapPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_PinMapPanel);
    lv_img_set_src(ui_Image3, &ui_img_pinmap_png);
    lv_obj_set_width(ui_Image3, lv_pct(49));
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image3, -68);
    lv_obj_set_y(ui_Image3, 1);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 200);

    ui_Label1 = lv_label_create(ui_PinMapPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 47);
    lv_obj_set_y(ui_Label1, -3);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "PinMap");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutPanel3 = lv_obj_create(ui_Container1);
    lv_obj_set_height(ui_AboutPanel3, 100);
    lv_obj_set_width(ui_AboutPanel3, lv_pct(100));
    lv_obj_set_x(ui_AboutPanel3, 72);
    lv_obj_set_y(ui_AboutPanel3, -269);
    lv_obj_set_align(ui_AboutPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AboutPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_AboutPanel3);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 46);
    lv_obj_set_y(ui_Label38, -2);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "DAPLink");
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_AboutPanel3);
    lv_img_set_src(ui_Image9, &ui_img_offline_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -67);
    lv_obj_set_y(ui_Image9, -2);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 150);

    ui_PWMPanel = lv_obj_create(ui_Container1);
    lv_obj_set_height(ui_PWMPanel, 100);
    lv_obj_set_width(ui_PWMPanel, lv_pct(100));
    lv_obj_set_x(ui_PWMPanel, -2);
    lv_obj_set_y(ui_PWMPanel, 105);
    lv_obj_set_align(ui_PWMPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PWMPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_PWMPanel);
    lv_img_set_src(ui_Image2, &ui_img_pwm_png);
    lv_obj_set_width(ui_Image2, lv_pct(48));
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image2, -68);
    lv_obj_set_y(ui_Image2, 1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 150);

    ui_Label3 = lv_label_create(ui_PWMPanel);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 49);
    lv_obj_set_y(ui_Label3, -3);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "PWM");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ElectricPanel = lv_obj_create(ui_Container1);
    lv_obj_set_height(ui_ElectricPanel, 100);
    lv_obj_set_width(ui_ElectricPanel, lv_pct(100));
    lv_obj_set_x(ui_ElectricPanel, 8);
    lv_obj_set_y(ui_ElectricPanel, -1);
    lv_obj_set_align(ui_ElectricPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ElectricPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_ElectricPanel);
    lv_img_set_src(ui_Image4, &ui_img_electric_png);
    lv_obj_set_width(ui_Image4, lv_pct(49));
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image4, -68);
    lv_obj_set_y(ui_Image4, 1);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 180);

    ui_Label4 = lv_label_create(ui_ElectricPanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 47);
    lv_obj_set_y(ui_Label4, -3);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Electric");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoisPanel = lv_obj_create(ui_Container1);
    lv_obj_set_height(ui_ServoisPanel, 100);
    lv_obj_set_width(ui_ServoisPanel, lv_pct(100));
    lv_obj_set_x(ui_ServoisPanel, 8);
    lv_obj_set_y(ui_ServoisPanel, -1);
    lv_obj_set_align(ui_ServoisPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServoisPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_ServoisPanel);
    lv_img_set_src(ui_Image5, &ui_img_servos_png);
    lv_obj_set_width(ui_Image5, lv_pct(49));
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image5, -57);
    lv_obj_set_y(ui_Image5, 1);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 180);

    ui_Label5 = lv_label_create(ui_ServoisPanel);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 47);
    lv_obj_set_y(ui_Label5, -3);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Servos");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogicPanel = lv_obj_create(ui_Container1);
    lv_obj_set_height(ui_LogicPanel, 100);
    lv_obj_set_width(ui_LogicPanel, lv_pct(100));
    lv_obj_set_x(ui_LogicPanel, 8);
    lv_obj_set_y(ui_LogicPanel, -1);
    lv_obj_set_align(ui_LogicPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LogicPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_LogicPanel);
    lv_img_set_src(ui_Image6, &ui_img_logic_png);
    lv_obj_set_width(ui_Image6, lv_pct(47));
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image6, -68);
    lv_obj_set_y(ui_Image6, 2);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 150);

    ui_Label6 = lv_label_create(ui_LogicPanel);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 47);
    lv_obj_set_y(ui_Label6, -3);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Logic");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DACPanel = lv_obj_create(ui_Container1);
    lv_obj_set_height(ui_DACPanel, 100);
    lv_obj_set_width(ui_DACPanel, lv_pct(100));
    lv_obj_set_x(ui_DACPanel, 8);
    lv_obj_set_y(ui_DACPanel, -1);
    lv_obj_set_align(ui_DACPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DACPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_DACPanel);
    lv_img_set_src(ui_Image7, &ui_img_waveform_png);
    lv_obj_set_width(ui_Image7, lv_pct(47));
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image7, -68);
    lv_obj_set_y(ui_Image7, 2);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 150);

    ui_Label7 = lv_label_create(ui_DACPanel);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 44);
    lv_obj_set_y(ui_Label7, 2);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "DAC");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PinMapPanel, ui_event_PinMapPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AboutPanel3, ui_event_AboutPanel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PWMPanel, ui_event_PWMPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ElectricPanel, ui_event_ElectricPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ServoisPanel, ui_event_ServoisPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LogicPanel, ui_event_LogicPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DACPanel, ui_event_DACPanel, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_deinit(void){

}