// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#include "../ui.h"

Page_t PageLogic = {
        .id = LogicPage,
        .init = ui_LogicScreen_screen_init,
        .deinit = ui_LogicScreen_screen_deinit,
        .page_obj = &ui_LogicScreen,
};

void ui_LogicScreen_screen_init(void)
{
    ui_LogicScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LogicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel35 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel35, 221);
    lv_obj_set_height(ui_Panel35, 115);
    lv_obj_set_x(ui_Panel35, -1);
    lv_obj_set_y(ui_Panel35, -49);
    lv_obj_set_align(ui_Panel35, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel35, lv_color_hex(0x0D0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel35, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_LogicScreen);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, -37);
    lv_obj_set_y(ui_Label63, -53);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "100");
    lv_obj_set_style_text_decor(ui_Label63, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_LogicScreen);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 41);
    lv_obj_set_y(ui_Label65, -61);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "MHz(max)");

    ui_Label66 = lv_label_create(ui_LogicScreen);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, 40);
    lv_obj_set_y(ui_Label66, -42);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "Sampling");

    ui_Panel38 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel38, 20);
    lv_obj_set_height(ui_Panel38, 72);
    lv_obj_set_x(ui_Panel38, -105);
    lv_obj_set_y(ui_Panel38, 93);
    lv_obj_set_align(ui_Panel38, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel38, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_Panel38);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, -1);
    lv_obj_set_y(ui_Label68, 0);
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "C\nH\n0");

    ui_Panel39 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel39, 20);
    lv_obj_set_height(ui_Panel39, 72);
    lv_obj_set_x(ui_Panel39, -75);
    lv_obj_set_y(ui_Panel39, 93);
    lv_obj_set_align(ui_Panel39, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel39, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label69 = lv_label_create(ui_Panel39);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, -1);
    lv_obj_set_y(ui_Label69, 0);
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "C\nH\n 1");

    ui_Panel40 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel40, 20);
    lv_obj_set_height(ui_Panel40, 72);
    lv_obj_set_x(ui_Panel40, -45);
    lv_obj_set_y(ui_Panel40, 94);
    lv_obj_set_align(ui_Panel40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel40, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label70 = lv_label_create(ui_Panel40);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label70, -1);
    lv_obj_set_y(ui_Label70, 0);
    lv_obj_set_align(ui_Label70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label70, "C\nH\n2");

    ui_Panel41 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel41, 20);
    lv_obj_set_height(ui_Panel41, 72);
    lv_obj_set_x(ui_Panel41, -15);
    lv_obj_set_y(ui_Panel41, 93);
    lv_obj_set_align(ui_Panel41, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel41, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label71 = lv_label_create(ui_Panel41);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label71, -1);
    lv_obj_set_y(ui_Label71, 0);
    lv_obj_set_align(ui_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label71, "C\nH\n3");

    ui_Panel42 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel42, 20);
    lv_obj_set_height(ui_Panel42, 72);
    lv_obj_set_x(ui_Panel42, 15);
    lv_obj_set_y(ui_Panel42, 93);
    lv_obj_set_align(ui_Panel42, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel42, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label72 = lv_label_create(ui_Panel42);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label72, -1);
    lv_obj_set_y(ui_Label72, 0);
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "C\nH\n4");

    ui_Panel43 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel43, 20);
    lv_obj_set_height(ui_Panel43, 72);
    lv_obj_set_x(ui_Panel43, 45);
    lv_obj_set_y(ui_Panel43, 93);
    lv_obj_set_align(ui_Panel43, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel43, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label73 = lv_label_create(ui_Panel43);
    lv_obj_set_width(ui_Label73, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label73, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label73, -1);
    lv_obj_set_y(ui_Label73, 0);
    lv_obj_set_align(ui_Label73, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label73, "C\nH\n5");

    ui_Panel44 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel44, 20);
    lv_obj_set_height(ui_Panel44, 72);
    lv_obj_set_x(ui_Panel44, 75);
    lv_obj_set_y(ui_Panel44, 93);
    lv_obj_set_align(ui_Panel44, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel44, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label74 = lv_label_create(ui_Panel44);
    lv_obj_set_width(ui_Label74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label74, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label74, 0);
    lv_obj_set_y(ui_Label74, 1);
    lv_obj_set_align(ui_Label74, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label74, "C\nH\n6");

    ui_Panel45 = lv_obj_create(ui_LogicScreen);
    lv_obj_set_width(ui_Panel45, 20);
    lv_obj_set_height(ui_Panel45, 72);
    lv_obj_set_x(ui_Panel45, 105);
    lv_obj_set_y(ui_Panel45, 93);
    lv_obj_set_align(ui_Panel45, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel45, lv_color_hex(0x50E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label75 = lv_label_create(ui_Panel45);
    lv_obj_set_width(ui_Label75, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label75, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label75, -1);
    lv_obj_set_y(ui_Label75, 0);
    lv_obj_set_align(ui_Label75, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label75, "C\nH\n7");

    ui_Label67 = lv_label_create(ui_LogicScreen);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, -68);
    lv_obj_set_y(ui_Label67, 35);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "ROM-2(1~8)");

    ui_Label76 = lv_label_create(ui_LogicScreen);
    lv_obj_set_width(ui_Label76, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label76, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label76, -31);
    lv_obj_set_y(ui_Label76, -122);
    lv_obj_set_align(ui_Label76, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label76, "Connect to PulseView");

    lv_obj_add_event_cb(ui_LogicScreen, ui_event_LogicScreen, LV_EVENT_ALL, NULL);

}
void ui_LogicScreen_screen_deinit(void){

}
