// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: offlineDownloadTest

#include "../ui.h"

void ui_OfflineDownload_screen_init(void)
{
    ui_OfflineDownload = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OfflineDownload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_OfflineDownload);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(15));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x35C1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "offline Download");

    ui_TypeSelectBtn = lv_btn_create(ui_OfflineDownload);
    lv_obj_set_width(ui_TypeSelectBtn, 85);
    lv_obj_set_height(ui_TypeSelectBtn, 50);
    lv_obj_set_x(ui_TypeSelectBtn, -72);
    lv_obj_set_y(ui_TypeSelectBtn, -62);
    lv_obj_set_align(ui_TypeSelectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TypeSelectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TypeSelectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_TypeSelectBtn);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Type");

    ui_BinSelectBtn = lv_btn_create(ui_OfflineDownload);
    lv_obj_set_width(ui_BinSelectBtn, 85);
    lv_obj_set_height(ui_BinSelectBtn, 50);
    lv_obj_set_x(ui_BinSelectBtn, -72);
    lv_obj_set_y(ui_BinSelectBtn, 3);
    lv_obj_set_align(ui_BinSelectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BinSelectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BinSelectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_BinSelectBtn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Bin");

    ui_StartBtn = lv_btn_create(ui_OfflineDownload);
    lv_obj_set_width(ui_StartBtn, 85);
    lv_obj_set_height(ui_StartBtn, 50);
    lv_obj_set_x(ui_StartBtn, -72);
    lv_obj_set_y(ui_StartBtn, 64);
    lv_obj_set_align(ui_StartBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_StartBtn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Start");

    ui_panel3 = lv_obj_create(ui_OfflineDownload);
    lv_obj_set_width(ui_panel3, 133);
    lv_obj_set_height(ui_panel3, 50);
    lv_obj_set_x(ui_panel3, 44);
    lv_obj_set_y(ui_panel3, -61);
    lv_obj_set_align(ui_panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SelectChipType = lv_label_create(ui_panel3);
    lv_obj_set_width(ui_SelectChipType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectChipType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SelectChipType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectChipType, "Chip Type");

    ui_Panel4 = lv_obj_create(ui_OfflineDownload);
    lv_obj_set_width(ui_Panel4, 133);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, 44);
    lv_obj_set_y(ui_Panel4, 2);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SelectBin = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_SelectBin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectBin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SelectBin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectBin, "SelectBin");

    ui_Panel5 = lv_obj_create(ui_OfflineDownload);
    lv_obj_set_width(ui_Panel5, 78);
    lv_obj_set_height(ui_Panel5, 29);
    lv_obj_set_x(ui_Panel5, 66);
    lv_obj_set_y(ui_Panel5, 54);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SuccessCount = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_SuccessCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SuccessCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SuccessCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SuccessCount, "0");

    ui_Label11 = lv_label_create(ui_OfflineDownload);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 55);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Count:");

    ui_Label12 = lv_label_create(ui_OfflineDownload);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 42);
    lv_obj_set_y(ui_Label12, 82);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Wait for Start");

    ui_uiOfflineDownloadProcessBar = lv_bar_create(ui_OfflineDownload);
    lv_bar_set_value(ui_uiOfflineDownloadProcessBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_uiOfflineDownloadProcessBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_uiOfflineDownloadProcessBar, 210);
    lv_obj_set_height(ui_uiOfflineDownloadProcessBar, 23);
    lv_obj_set_x(ui_uiOfflineDownloadProcessBar, -4);
    lv_obj_set_y(ui_uiOfflineDownloadProcessBar, 114);
    lv_obj_set_align(ui_uiOfflineDownloadProcessBar, LV_ALIGN_CENTER);

    ui_uiOfflineDownloadProcessNum = lv_label_create(ui_uiOfflineDownloadProcessBar);
    lv_obj_set_width(ui_uiOfflineDownloadProcessNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiOfflineDownloadProcessNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiOfflineDownloadProcessNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiOfflineDownloadProcessNum, "0%");

    lv_obj_add_event_cb(ui_TypeSelectBtn, ui_event_TypeSelectBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BinSelectBtn, ui_event_BinSelectBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartBtn, ui_event_StartBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OfflineDownload, ui_event_OfflineDownload, LV_EVENT_ALL, NULL);

}
