// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#include "../ui.h"

Page_t PageOffline = {
        .init = ui_OfflineScreen_screen_init,
        .deinit = ui_OfflineScreen_screen_deinit,
        .page_obj = &ui_OfflineScreen,
};

void ui_OfflineScreen_screen_init(void)
{
    ui_OfflineScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OfflineScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SelectChip = lv_btn_create(ui_OfflineScreen);
    lv_obj_set_width(ui_SelectChip, 83);
    lv_obj_set_height(ui_SelectChip, 50);
    lv_obj_set_x(ui_SelectChip, -71);
    lv_obj_set_y(ui_SelectChip, -104);
    lv_obj_set_align(ui_SelectChip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SelectChip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectChip, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_SelectChip);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Chip");

    ui_SelectFirm = lv_btn_create(ui_OfflineScreen);
    lv_obj_set_width(ui_SelectFirm, 83);
    lv_obj_set_height(ui_SelectFirm, 50);
    lv_obj_set_x(ui_SelectFirm, -70);
    lv_obj_set_y(ui_SelectFirm, -40);
    lv_obj_set_align(ui_SelectFirm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SelectFirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectFirm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_SelectFirm);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "firmware");

    ui_FirmDown = lv_btn_create(ui_OfflineScreen);
    lv_obj_set_width(ui_FirmDown, 107);
    lv_obj_set_height(ui_FirmDown, 50);
    lv_obj_set_x(ui_FirmDown, -2);
    lv_obj_set_y(ui_FirmDown, 79);
    lv_obj_set_align(ui_FirmDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FirmDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FirmDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_FirmDown);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "Start");

    ui_Panel22 = lv_obj_create(ui_OfflineScreen);
    lv_obj_set_width(ui_Panel22, 132);
    lv_obj_set_height(ui_Panel22, 50);
    lv_obj_set_x(ui_Panel22, 44);
    lv_obj_set_y(ui_Panel22, -103);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChipLabel = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_ChipLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChipLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChipLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChipLabel, "Select Chip");

    ui_Panel24 = lv_obj_create(ui_OfflineScreen);
    lv_obj_set_width(ui_Panel24, 131);
    lv_obj_set_height(ui_Panel24, 50);
    lv_obj_set_x(ui_Panel24, 44);
    lv_obj_set_y(ui_Panel24, -41);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FirmWareLabel = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_FirmWareLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FirmWareLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FirmWareLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FirmWareLabel, "Select firmware");

    ui_DownBar = lv_bar_create(ui_OfflineScreen);
    lv_bar_set_value(ui_DownBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_DownBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DownBar, 214);
    lv_obj_set_height(ui_DownBar, 25);
    lv_obj_set_x(ui_DownBar, 0);
    lv_obj_set_y(ui_DownBar, 9);
    lv_obj_set_align(ui_DownBar, LV_ALIGN_CENTER);

    ui_DownProgress = lv_label_create(ui_DownBar);
    lv_obj_set_width(ui_DownProgress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownProgress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DownProgress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DownProgress, "0%");

    ui_DownInfo = lv_label_create(ui_OfflineScreen);
    lv_obj_set_width(ui_DownInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownInfo, 0);
    lv_obj_set_y(ui_DownInfo, 40);
    lv_obj_set_align(ui_DownInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DownInfo, "Wait for Start");
    lv_obj_set_style_text_font(ui_DownInfo, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_OfflineScreen);
    lv_obj_set_width(ui_Panel26, 67);
    lv_obj_set_height(ui_Panel26, 28);
    lv_obj_set_x(ui_Panel26, -1);
    lv_obj_set_y(ui_Panel26, 124);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0xFFCF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Panel26);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, -2);
    lv_obj_set_y(ui_Label46, 0);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "SWD: 7");

    ui_Label45 = lv_label_create(ui_OfflineScreen);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -87);
    lv_obj_set_y(ui_Label45, 124);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "ROW1");

    ui_Panel27 = lv_obj_create(ui_OfflineScreen);
    lv_obj_set_width(ui_Panel27, 68);
    lv_obj_set_height(ui_Panel27, 28);
    lv_obj_set_x(ui_Panel27, 72);
    lv_obj_set_y(ui_Panel27, 124);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0x2AC15A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Panel27);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -2);
    lv_obj_set_y(ui_Label47, 0);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "SWC: 8");

    lv_obj_add_event_cb(ui_OfflineScreen, ui_event_OfflineScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SelectChip,ui_event_OfflineChipSelect,LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SelectFirm, ui_event_OfflineFirmSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FirmDown, ui_event_OfflineFirmDownload, LV_EVENT_ALL, NULL);

}

void ui_OfflineScreen_screen_deinit(void){

}