// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#include "../ui.h"

Page_t PagePWM = {
        .id = PWMPage,
        .init = ui_PWMScreen_screen_init,
        .deinit = ui_PWMScreen_screen_deinit,
        .page_obj = &ui_PWMScreen,
};

void ui_PWMScreen_screen_init(void)
{
    ui_PWMScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PWMScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_PWMScreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 210);
    lv_obj_set_height(ui_Container3, 44);
    lv_obj_set_x(ui_Container3, -1);
    lv_obj_set_y(ui_Container3, -84);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -80);
    lv_obj_set_y(ui_Label30, -87);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Period\n   (ns)");
    lv_obj_set_style_pad_left(ui_Label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label30, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label30, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    keyboard = lv_keyboard_create(ui_PWMScreen);
    lv_keyboard_set_mode(keyboard, LV_KEYBOARD_MODE_NUMBER);//ÉèÖÃÎªÊý×ÖÐ¡¼üÅÌ
    lv_obj_add_flag(keyboard, LV_OBJ_FLAG_HIDDEN);  // Ä¬ÈÏÒþ²Ø¼üÅÌ

    ui_PWMPeriod = lv_textarea_create(ui_Container3);
    lv_obj_set_width(ui_PWMPeriod, 150);
    lv_obj_set_height(ui_PWMPeriod, 42);
    lv_obj_set_x(ui_PWMPeriod, 46);
    lv_obj_set_y(ui_PWMPeriod, -85);
    lv_obj_set_align(ui_PWMPeriod, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PWMPeriod, "Period...");



    ui_Container4 = lv_obj_create(ui_PWMScreen);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 210);
    lv_obj_set_height(ui_Container4, 44);
    lv_obj_set_x(ui_Container4, 3);
    lv_obj_set_y(ui_Container4, -34);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -80);
    lv_obj_set_y(ui_Label33, -87);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Pulse \n  (ns) ");
    lv_obj_set_style_pad_left(ui_Label33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label33, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label33, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMPulse = lv_textarea_create(ui_Container4);
    lv_obj_set_width(ui_PWMPulse, 150);
    lv_obj_set_height(ui_PWMPulse, 42);
    lv_obj_set_x(ui_PWMPulse, 43);
    lv_obj_set_y(ui_PWMPulse, -85);
    lv_obj_set_align(ui_PWMPulse, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PWMPulse, "Pulse...");



    ui_Container5 = lv_obj_create(ui_PWMScreen);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 194);
    lv_obj_set_height(ui_Container5, 37);
    lv_obj_set_x(ui_Container5, 3);
    lv_obj_set_y(ui_Container5, 27);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label32 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -78);
    lv_obj_set_y(ui_Label32, 2);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Freq:  ");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMFreqLabel = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_PWMFreqLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWMFreqLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWMFreqLabel, 24);
    lv_obj_set_y(ui_PWMFreqLabel, 0);
    lv_obj_set_align(ui_PWMFreqLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWMFreqLabel, "0.0MHz");
    lv_obj_set_style_text_font(ui_PWMFreqLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_PWMScreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 196);
    lv_obj_set_height(ui_Container6, 37);
    lv_obj_set_x(ui_Container6, 3);
    lv_obj_set_y(ui_Container6, 75);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -78);
    lv_obj_set_y(ui_Label37, 2);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Duty:  ");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMDutyLabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_PWMDutyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWMDutyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PWMDutyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWMDutyLabel, "00.00%");
    lv_obj_set_style_text_font(ui_PWMDutyLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_PWMScreen);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -88);
    lv_obj_set_y(ui_Label48, 124);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "ROW2");

    ui_Panel29 = lv_obj_create(ui_PWMScreen);
    lv_obj_set_width(ui_Panel29, 67);
    lv_obj_set_height(ui_Panel29, 28);
    lv_obj_set_x(ui_Panel29, 1);
    lv_obj_set_y(ui_Panel29, 124);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0xA85432), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "PWM: 8");

    ui_Panel30 = lv_obj_create(ui_PWMScreen);
    lv_obj_set_width(ui_Panel30, 67);
    lv_obj_set_height(ui_Panel30, 28);
    lv_obj_set_x(ui_Panel30, 77);
    lv_obj_set_y(ui_Panel30, 124);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0xA85432), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -2);
    lv_obj_set_y(ui_Label51, 0);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "PWM: 9");

    lv_obj_add_event_cb(ui_PWMPeriod, ui_event_PWMPeriod, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PWMPulse, ui_event_PWMPulse, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(keyboard, ui_event_KeyBoard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PWMScreen, ui_event_PWMScreen, LV_EVENT_ALL, NULL);

}

void ui_PWMScreen_screen_deinit(void){

}