// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HonestLink

#include "../ui.h"

Page_t PageServos = {
        .id = ServosPage,
        .init = ui_ServosScreen_screen_init,
        .deinit = ui_ServosScreen_screen_deinit,
        .page_obj = &ui_ServosScreen,
};

void ui_ServosScreen_screen_init(void)
{
    ui_ServosScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ServosScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ServoArc = lv_arc_create(ui_ServosScreen);
    lv_obj_set_width(ui_ServoArc, 150);
    lv_obj_set_height(ui_ServoArc, 150);
    lv_obj_set_x(ui_ServoArc, -2);
    lv_obj_set_y(ui_ServoArc, 10);
    lv_obj_set_align(ui_ServoArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ServoArc, 0, 180);
    lv_arc_set_value(ui_ServoArc, 0);
    lv_obj_set_style_arc_width(ui_ServoArc, 18, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_ServoLabel = lv_label_create(ui_ServosScreen);
    lv_obj_set_width(ui_ServoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoLabel, -3);
    lv_obj_set_y(ui_ServoLabel, 5);
    lv_obj_set_align(ui_ServoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServoLabel, "0");
    lv_obj_set_style_text_font(ui_ServoLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_ServosScreen);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, 1);
    lv_obj_set_y(ui_Label60, -117);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "Servo Controler");
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_ServosScreen);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, -3);
    lv_obj_set_y(ui_Label61, 46);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "Degrees");

    ui_Label62 = lv_label_create(ui_ServosScreen);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, -80);
    lv_obj_set_y(ui_Label62, 120);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "ROW2");

    ui_Panel36 = lv_obj_create(ui_ServosScreen);
    lv_obj_set_width(ui_Panel36, 67);
    lv_obj_set_height(ui_Panel36, 28);
    lv_obj_set_x(ui_Panel36, 80);
    lv_obj_set_y(ui_Panel36, 120);
    lv_obj_set_align(ui_Panel36, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel36, lv_color_hex(0xA85432), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label64 = lv_label_create(ui_Panel36);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, -2);
    lv_obj_set_y(ui_Label64, 0);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "PWM: 9");

    lv_obj_add_event_cb(ui_ServosScreen, ui_event_ServosScreen, LV_EVENT_ALL, NULL);

}

void ui_ServosScreen_screen_deinit(void){

}